import argparse
import configparser
import getpass
import logging
import os
import re
from argparse import _StoreAction, _StoreFalseAction, _StoreTrueAction
from typing import Any, Dict, List, Optional, Tuple

from revup.types import RevupUsageException


class RevupArgParser(argparse.ArgumentParser):
    def add_argument(self, *args: Any, **kwargs: Any) -> argparse.Action:
        """
        For each boolean store_true action, add a corresponding "no" store_false action
        with the same target.
        """
        completable = kwargs.pop("completable", True)
        action = super().add_argument(*args, **kwargs)
        action.completable = completable  # type: ignore[attr-defined]

        if isinstance(action, _StoreTrueAction):
            no_options = []
            for option_string in action.option_strings:
                if option_string.startswith("--"):
                    no_options.append("--no-" + option_string[2:])

            if no_options:
                neg_action = _StoreFalseAction(
                    no_options,
                    action.dest,
                    action.default,
                    False,
                    "autogenerated negation",
                )
                neg_action.completable = (  # type: ignore[attr-defined]
                    completable and action.default is True
                )
                for op in no_options:
                    self._option_string_actions[op] = neg_action
                self._actions.append(neg_action)
        elif isinstance(action, _StoreFalseAction):
            # We assume all store false actions are the autogenerated one
            raise RuntimeError("Direct store_false actions are not allowed")

        return action

    def collect_excluded_completions(self) -> List[str]:
        excluded = []
        for action in self._actions:
            completable = getattr(action, "completable", False)
            for opt in action.option_strings:
                if not completable or not opt.startswith("--"):
                    excluded.append(opt)
            if hasattr(action, "choices") and isinstance(action.choices, dict):
                for sp in action.choices.values():
                    if isinstance(sp, RevupArgParser):
                        excluded.extend(sp.collect_excluded_completions())
        return excluded

    def set_defaults_from_config(self, conf: configparser.ConfigParser) -> None:
        cmd = self.get_command()
        for option, action in self.get_actions().items():
            if conf.has_option(cmd, option):
                self.set_option_default(option, action, conf.get(cmd, option))

    def get_command(self) -> str:
        return self.prog.split()[-1].replace("-", "_")

    def get_actions(self) -> Dict[str, argparse.Action]:
        ret: Dict[str, argparse.Action] = {}
        for action in self._actions:
            if not isinstance(action, (_StoreTrueAction, _StoreAction)):
                # Ignore nonconfigurable actions (help, auto-generated negation)
                continue

            for opt in action.option_strings:
                if opt.startswith("--"):
                    option = opt[2:].replace("-", "_")
                    ret.setdefault(option, action)
        return ret

    def set_option_default(self, option: str, action: argparse.Action, value: str) -> None:
        if isinstance(action, _StoreTrueAction):
            override = value.lower()
            if override in ("true", "false"):
                action.default = override == "true"
            else:
                raise ValueError(
                    f'"{override}" not a valid override for boolean flag {option}, must'
                    ' be "true" or "false"'
                )
        elif isinstance(action, _StoreAction):
            if action.choices and value not in action.choices:
                raise ValueError(
                    f"Value {value} for {self.get_command()}.{option} is not"
                    f" one of the choices {action.choices}"
                )

            action.default = value
        else:
            raise RuntimeError("Unknown option type!: ", option, action)


class Config:
    # Object containing configuration values. Populated by read(), and can then
    # be modified by set_value()
    config: configparser.ConfigParser

    # Path to user global config file
    config_path: str

    # Path to config file in current repo
    repo_config_path: str

    # Path to config file inside the current repo's .git directory
    git_dir_config_path: str

    # Whether the config contains values that need to be flushed to the file
    dirty: bool = False

    def __init__(
        self,
        config_path: str,
        repo_config_path: str = "",
        git_dir_config_path: str = "",
    ):
        self.config = configparser.ConfigParser()
        self.config_path = config_path
        self.repo_config_path = repo_config_path
        self.git_dir_config_path = git_dir_config_path
        self.file_configs: List[Tuple[str, configparser.ConfigParser]] = []

    def read(self) -> None:
        # Read in increasing precedence: later reads overwrite earlier ones.
        # Precedence: .git/.revupconfig > repo/.revupconfig > ~/.revupconfig
        for path in (self.config_path, self.repo_config_path, self.git_dir_config_path):
            if not path:
                continue
            file_conf = configparser.ConfigParser()
            if file_conf.read(path):
                self.file_configs.append((path, file_conf))
            self.config.read(path)

    def write(self) -> None:
        if not self.dirty:
            return

        # Ensure the file is created with secure permissions, due to containing credentials
        with os.fdopen(
            os.open(self.config_path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600), "w"
        ) as f:
            self.config.write(f)
        self.dirty = False

    def set_value(self, section: str, key: str, value: Optional[str]) -> None:
        if value is None:
            if self.config.has_option(section, key):
                self.config.remove_option(section, key)
                self.dirty = True
            return

        if not self.config.has_section(section):
            self.config.add_section(section)
            self.dirty = True

        if not self.config.has_option(section, key) or self.config.get(section, key) != value:
            self.config.set(section, key, value)
            self.dirty = True

    def get_config(self) -> configparser.ConfigParser:
        return self.config

    def apply_to_parsers(self, all_parsers: List[RevupArgParser]) -> None:
        for p in all_parsers:
            p.set_defaults_from_config(self.config)
        known = collect_known_keys(all_parsers)
        for path, file_conf in self.file_configs:
            for section in file_conf.sections():
                known_keys = known.get(section)
                if known_keys is None:
                    logging.warning(f"Unrecognized config section [{section}] in {path}")
                    continue
                for key in file_conf.options(section):
                    if key not in known_keys:
                        logging.warning(f"Unrecognized config key {section}.{key} in {path}")


def collect_known_keys(all_parsers: List[RevupArgParser]) -> Dict[str, List[str]]:
    return {p.get_command(): list(p.get_actions().keys()) for p in all_parsers}


def config_main(conf: Config, args: argparse.Namespace, all_parsers: List[RevupArgParser]) -> int:
    split_key = args.flag[0].replace("-", "_").split(".")
    if len(split_key) == 1:
        command = "revup"
        key = split_key[0]
    elif len(split_key) == 2:
        command = split_key[0]
        key = split_key[1]
    else:
        raise RevupUsageException("Invalid flag argument (must be <key> or <command>.<key>)")

    all_commands = {p.get_command(): p for p in all_parsers}
    if command not in all_commands:
        raise RevupUsageException(
            f"Invalid command section {command}, choose from {list(all_commands.keys())}"
        )

    parser = all_commands[command]
    actions = parser.get_actions()

    if not args.delete:
        if key not in actions:
            raise RevupUsageException(
                f"Invalid option key {key}, choose from {list(actions.keys())}"
            )

    if args.delete:
        value = None
        if args.value:
            raise RevupUsageException(
                f"Can't provide a value {args.value} for {command}.{key} when using --delete"
            )
    elif args.value:
        value = args.value
        if command == "revup" and key in ("forge_oauth", "github_oauth"):
            logging.warning(
                "Prefer to omit the value on command line when entering sensitive info. "
                "You may want to clear your shell history."
            )
    else:
        value = getpass.getpass(f"Input value for {command}.{key}: ").strip()

    if sum(bool(x) for x in (args.use_global, args.repo, args.repo_local)) > 1:
        raise RevupUsageException("Can only specify one of --global, --repo, or --repo-local")
    if args.repo_local:
        config_path = conf.git_dir_config_path
    elif args.repo:
        config_path = conf.repo_config_path
    else:
        config_path = conf.config_path
    this_config = Config(config_path)
    this_config.read()

    if value is not None:
        # Check whether this value is allowed by the parser by attempting to set it
        # (this may throw if the value is not allowed)
        parser.set_option_default(key, actions[key], value)

        if command == "revup" and key in ("forge_oauth", "github_oauth"):
            if not re.match(r"^[a-z\d_]+$", value, re.I):
                raise ValueError("Input string is not a valid oauth")

    this_config.set_value(command, key, value)
    this_config.write()
    return 0
