# Generated by ariadne-codegen
# Source: revup/github/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class AddComment(BaseModel):
    add_comment: Optional["AddCommentAddComment"] = Field(alias="addComment")


class AddCommentAddComment(BaseModel):
    client_mutation_id: Optional[str] = Field(alias="clientMutationId")


AddComment.model_rebuild()
