# Generated by ariadne-codegen
# Source: revup/github/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class AddAssignees(BaseModel):
    add_assignees_to_assignable: Optional["AddAssigneesAddAssigneesToAssignable"] = Field(
        alias="addAssigneesToAssignable"
    )


class AddAssigneesAddAssigneesToAssignable(BaseModel):
    client_mutation_id: Optional[str] = Field(alias="clientMutationId")


AddAssignees.model_rebuild()
