# Generated by ariadne-codegen
# Source: revup/github/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class AddLabels(BaseModel):
    add_labels_to_labelable: Optional["AddLabelsAddLabelsToLabelable"] = Field(
        alias="addLabelsToLabelable"
    )


class AddLabelsAddLabelsToLabelable(BaseModel):
    client_mutation_id: Optional[str] = Field(alias="clientMutationId")


AddLabels.model_rebuild()
