# Generated by ariadne-codegen
# Source: revup/github/queries/

from typing import Any, Dict

from revup.github.base_client import GitHubBaseClient

from .add_assignees import AddAssignees
from .add_comment import AddComment
from .add_labels import AddLabels
from .convert_to_draft import ConvertToDraft
from .create_pull_request import CreatePullRequest
from .get_assignable_users import GetAssignableUsers
from .get_label import GetLabel
from .get_pr_by_number import GetPrByNumber
from .get_pull_request import GetPullRequest
from .get_team import GetTeam
from .input_types import (
    AddAssigneesToAssignableInput,
    AddCommentInput,
    AddLabelsToLabelableInput,
    ConvertPullRequestToDraftInput,
    CreatePullRequestInput,
    MarkPullRequestReadyForReviewInput,
    RequestReviewsInput,
    UpdateIssueCommentInput,
    UpdatePullRequestInput,
)
from .mark_ready_for_review import MarkReadyForReview
from .request_reviews import RequestReviews
from .update_issue_comment import UpdateIssueComment
from .update_pull_request import UpdatePullRequest


def gql(q: str) -> str:
    return q


ADD_ASSIGNEES_QUERY = gql(
    """
mutation AddAssignees($input: AddAssigneesToAssignableInput!) {
  addAssigneesToAssignable(input: $input) {
    clientMutationId
  }
}
"""
)

ADD_COMMENT_QUERY = gql(
    """
mutation AddComment($input: AddCommentInput!) {
  addComment(input: $input) {
    clientMutationId
  }
}
"""
)

ADD_LABELS_QUERY = gql(
    """
mutation AddLabels($input: AddLabelsToLabelableInput!) {
  addLabelsToLabelable(input: $input) {
    clientMutationId
  }
}
"""
)

CONVERT_TO_DRAFT_QUERY = gql(
    """
mutation ConvertToDraft($input: ConvertPullRequestToDraftInput!) {
  convertPullRequestToDraft(input: $input) {
    clientMutationId
  }
}
"""
)

CREATE_PULL_REQUEST_QUERY = gql(
    """
mutation CreatePullRequest($input: CreatePullRequestInput!) {
  createPullRequest(input: $input) {
    pullRequest {
      id
      url
    }
  }
}
"""
)

GET_ASSIGNABLE_USERS_QUERY = gql(
    """
query GetAssignableUsers($owner: String!, $name: String!, $query: String!) {
  repository(owner: $owner, name: $name) {
    assignableUsers(query: $query, first: 25) {
      nodes {
        login
        id
      }
      totalCount
    }
  }
}
"""
)

GET_LABEL_QUERY = gql(
    """
query GetLabel($owner: String!, $name: String!, $labelName: String!) {
  repository(owner: $owner, name: $name) {
    label(name: $labelName) {
      id
      name
    }
  }
}
"""
)

GET_PR_BY_NUMBER_QUERY = gql(
    """
query GetPrByNumber($owner: String!, $name: String!, $number: Int!) {
  repository(owner: $owner, name: $name) {
    pullRequest(number: $number) {
      headRefName
      baseRefName
    }
  }
}
"""
)

GET_PULL_REQUEST_QUERY = gql(
    """
query GetPullRequest($owner: String!, $name: String!, $headRefName: String!, $maxComments: Int!) {
  repository(owner: $owner, name: $name) {
    id
    pullRequests(
      headRefName: $headRefName
      states: [OPEN, MERGED]
      first: 1
      orderBy: {direction: DESC, field: UPDATED_AT}
    ) {
      nodes {
        id
        state
        url
        baseRefName
        body
        title
        isDraft
        baseCommit: commits(first: 1) {
          nodes {
            commit {
              parents(first: 1) {
                nodes {
                  oid
                }
              }
            }
          }
        }
        headCommit: commits(last: 1) {
          nodes {
            commit {
              oid
            }
          }
        }
        reviewRequests(first: 25) {
          nodes {
            requestedReviewer {
              __typename
              ... on User {
                login
                id
              }
              ... on Team {
                slug
                id
                organization {
                  login
                }
              }
            }
          }
        }
        timelineItems(
          itemTypes: [REVIEW_REQUEST_REMOVED_EVENT, UNASSIGNED_EVENT]
          first: 50
        ) {
          nodes {
            __typename
            ... on ReviewRequestRemovedEvent {
              requestedReviewer {
                __typename
                ... on User {
                  login
                  id
                }
              }
            }
            ... on UnassignedEvent {
              assignee {
                __typename
                ... on User {
                  login
                  id
                }
              }
            }
          }
        }
        latestReviews(first: 25) {
          nodes {
            author {
              __typename
              ... on User {
                login
                id
              }
            }
            viewerDidAuthor
          }
        }
        assignees(first: 25) {
          nodes {
            ... on User {
              login
              id
            }
          }
        }
        labels(first: 25) {
          nodes {
            name
            id
          }
        }
        comments(first: $maxComments) {
          nodes {
            body
            id
          }
        }
      }
      totalCount
    }
  }
}
"""
)

GET_TEAM_QUERY = gql(
    """
query GetTeam($org: String!, $slug: String!) {
  organization(login: $org) {
    team(slug: $slug) {
      id
      members(first: 100) {
        nodes {
          login
        }
        totalCount
      }
    }
  }
}
"""
)

MARK_READY_FOR_REVIEW_QUERY = gql(
    """
mutation MarkReadyForReview($input: MarkPullRequestReadyForReviewInput!) {
  markPullRequestReadyForReview(input: $input) {
    clientMutationId
  }
}
"""
)

REQUEST_REVIEWS_QUERY = gql(
    """
mutation RequestReviews($input: RequestReviewsInput!) {
  requestReviews(input: $input) {
    clientMutationId
  }
}
"""
)

UPDATE_ISSUE_COMMENT_QUERY = gql(
    """
mutation UpdateIssueComment($input: UpdateIssueCommentInput!) {
  updateIssueComment(input: $input) {
    clientMutationId
  }
}
"""
)

UPDATE_PULL_REQUEST_QUERY = gql(
    """
mutation UpdatePullRequest($input: UpdatePullRequestInput!) {
  updatePullRequest(input: $input) {
    clientMutationId
  }
}
"""
)


class GitHubGqlClient(GitHubBaseClient):
    def add_assignees_query(self) -> str:
        return ADD_ASSIGNEES_QUERY

    async def add_assignees(
        self, input: AddAssigneesToAssignableInput, **kwargs: Any
    ) -> AddAssignees:
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=ADD_ASSIGNEES_QUERY,
            operation_name="AddAssignees",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return AddAssignees.model_validate(data)

    def add_comment_query(self) -> str:
        return ADD_COMMENT_QUERY

    async def add_comment(self, input: AddCommentInput, **kwargs: Any) -> AddComment:
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=ADD_COMMENT_QUERY,
            operation_name="AddComment",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return AddComment.model_validate(data)

    def add_labels_query(self) -> str:
        return ADD_LABELS_QUERY

    async def add_labels(self, input: AddLabelsToLabelableInput, **kwargs: Any) -> AddLabels:
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=ADD_LABELS_QUERY,
            operation_name="AddLabels",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return AddLabels.model_validate(data)

    def convert_to_draft_query(self) -> str:
        return CONVERT_TO_DRAFT_QUERY

    async def convert_to_draft(
        self, input: ConvertPullRequestToDraftInput, **kwargs: Any
    ) -> ConvertToDraft:
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=CONVERT_TO_DRAFT_QUERY,
            operation_name="ConvertToDraft",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return ConvertToDraft.model_validate(data)

    def create_pull_request_query(self) -> str:
        return CREATE_PULL_REQUEST_QUERY

    async def create_pull_request(
        self, input: CreatePullRequestInput, **kwargs: Any
    ) -> CreatePullRequest:
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=CREATE_PULL_REQUEST_QUERY,
            operation_name="CreatePullRequest",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return CreatePullRequest.model_validate(data)

    def get_assignable_users_query(self) -> str:
        return GET_ASSIGNABLE_USERS_QUERY

    async def get_assignable_users(
        self, owner: str, name: str, query: str, **kwargs: Any
    ) -> GetAssignableUsers:
        variables: Dict[str, object] = {"owner": owner, "name": name, "query": query}
        response = await self.execute(
            query=GET_ASSIGNABLE_USERS_QUERY,
            operation_name="GetAssignableUsers",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return GetAssignableUsers.model_validate(data)

    def get_label_query(self) -> str:
        return GET_LABEL_QUERY

    async def get_label(self, owner: str, name: str, label_name: str, **kwargs: Any) -> GetLabel:
        variables: Dict[str, object] = {
            "owner": owner,
            "name": name,
            "labelName": label_name,
        }
        response = await self.execute(
            query=GET_LABEL_QUERY,
            operation_name="GetLabel",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return GetLabel.model_validate(data)

    def get_pr_by_number_query(self) -> str:
        return GET_PR_BY_NUMBER_QUERY

    async def get_pr_by_number(
        self, owner: str, name: str, number: int, **kwargs: Any
    ) -> GetPrByNumber:
        variables: Dict[str, object] = {"owner": owner, "name": name, "number": number}
        response = await self.execute(
            query=GET_PR_BY_NUMBER_QUERY,
            operation_name="GetPrByNumber",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return GetPrByNumber.model_validate(data)

    def get_pull_request_query(self) -> str:
        return GET_PULL_REQUEST_QUERY

    async def get_pull_request(
        self, owner: str, name: str, head_ref_name: str, max_comments: int, **kwargs: Any
    ) -> GetPullRequest:
        variables: Dict[str, object] = {
            "owner": owner,
            "name": name,
            "headRefName": head_ref_name,
            "maxComments": max_comments,
        }
        response = await self.execute(
            query=GET_PULL_REQUEST_QUERY,
            operation_name="GetPullRequest",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return GetPullRequest.model_validate(data)

    def get_team_query(self) -> str:
        return GET_TEAM_QUERY

    async def get_team(self, org: str, slug: str, **kwargs: Any) -> GetTeam:
        variables: Dict[str, object] = {"org": org, "slug": slug}
        response = await self.execute(
            query=GET_TEAM_QUERY,
            operation_name="GetTeam",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return GetTeam.model_validate(data)

    def mark_ready_for_review_query(self) -> str:
        return MARK_READY_FOR_REVIEW_QUERY

    async def mark_ready_for_review(
        self, input: MarkPullRequestReadyForReviewInput, **kwargs: Any
    ) -> MarkReadyForReview:
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=MARK_READY_FOR_REVIEW_QUERY,
            operation_name="MarkReadyForReview",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return MarkReadyForReview.model_validate(data)

    def request_reviews_query(self) -> str:
        return REQUEST_REVIEWS_QUERY

    async def request_reviews(self, input: RequestReviewsInput, **kwargs: Any) -> RequestReviews:
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=REQUEST_REVIEWS_QUERY,
            operation_name="RequestReviews",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return RequestReviews.model_validate(data)

    def update_issue_comment_query(self) -> str:
        return UPDATE_ISSUE_COMMENT_QUERY

    async def update_issue_comment(
        self, input: UpdateIssueCommentInput, **kwargs: Any
    ) -> UpdateIssueComment:
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=UPDATE_ISSUE_COMMENT_QUERY,
            operation_name="UpdateIssueComment",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return UpdateIssueComment.model_validate(data)

    def update_pull_request_query(self) -> str:
        return UPDATE_PULL_REQUEST_QUERY

    async def update_pull_request(
        self, input: UpdatePullRequestInput, **kwargs: Any
    ) -> UpdatePullRequest:
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=UPDATE_PULL_REQUEST_QUERY,
            operation_name="UpdatePullRequest",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return UpdatePullRequest.model_validate(data)
