# Generated by ariadne-codegen
# Source: revup/github/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class ConvertToDraft(BaseModel):
    convert_pull_request_to_draft: Optional["ConvertToDraftConvertPullRequestToDraft"] = Field(
        alias="convertPullRequestToDraft"
    )


class ConvertToDraftConvertPullRequestToDraft(BaseModel):
    client_mutation_id: Optional[str] = Field(alias="clientMutationId")


ConvertToDraft.model_rebuild()
