# Generated by ariadne-codegen
# Source: revup/github/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class CreatePullRequest(BaseModel):
    create_pull_request: Optional["CreatePullRequestCreatePullRequest"] = Field(
        alias="createPullRequest"
    )


class CreatePullRequestCreatePullRequest(BaseModel):
    pull_request: Optional["CreatePullRequestCreatePullRequestPullRequest"] = Field(
        alias="pullRequest"
    )


class CreatePullRequestCreatePullRequestPullRequest(BaseModel):
    id: str
    url: str


CreatePullRequest.model_rebuild()
CreatePullRequestCreatePullRequest.model_rebuild()
