# Generated by ariadne-codegen
# Source: revup/github/schema/github.graphql

from enum import Enum


class PullRequestState(str, Enum):
    CLOSED = "CLOSED"
    MERGED = "MERGED"
    OPEN = "OPEN"


class PullRequestUpdateState(str, Enum):
    CLOSED = "CLOSED"
    OPEN = "OPEN"
