# Generated by ariadne-codegen
# Source: revup/github/queries/

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class GetAssignableUsers(BaseModel):
    repository: Optional["GetAssignableUsersRepository"]


class GetAssignableUsersRepository(BaseModel):
    assignable_users: "GetAssignableUsersRepositoryAssignableUsers" = Field(alias="assignableUsers")


class GetAssignableUsersRepositoryAssignableUsers(BaseModel):
    nodes: Optional[List[Optional["GetAssignableUsersRepositoryAssignableUsersNodes"]]]
    total_count: int = Field(alias="totalCount")


class GetAssignableUsersRepositoryAssignableUsersNodes(BaseModel):
    login: str
    id: str


GetAssignableUsers.model_rebuild()
GetAssignableUsersRepository.model_rebuild()
GetAssignableUsersRepositoryAssignableUsers.model_rebuild()
