# Generated by ariadne-codegen
# Source: revup/github/queries/

from typing import Optional

from .base_model import BaseModel


class GetLabel(BaseModel):
    repository: Optional["GetLabelRepository"]


class GetLabelRepository(BaseModel):
    label: Optional["GetLabelRepositoryLabel"]


class GetLabelRepositoryLabel(BaseModel):
    id: str
    name: str


GetLabel.model_rebuild()
GetLabelRepository.model_rebuild()
