# Generated by ariadne-codegen
# Source: revup/github/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class GetPrByNumber(BaseModel):
    repository: Optional["GetPrByNumberRepository"]


class GetPrByNumberRepository(BaseModel):
    pull_request: Optional["GetPrByNumberRepositoryPullRequest"] = Field(alias="pullRequest")


class GetPrByNumberRepositoryPullRequest(BaseModel):
    head_ref_name: str = Field(alias="headRefName")
    base_ref_name: str = Field(alias="baseRefName")


GetPrByNumber.model_rebuild()
GetPrByNumberRepository.model_rebuild()
