# Generated by ariadne-codegen
# Source: revup/github/queries/

from typing import List, Optional, Union

from pydantic import Field
from typing_extensions import Annotated, Literal

from .base_model import BaseModel
from .enums import PullRequestState


class GetPullRequest(BaseModel):
    repository: Optional["GetPullRequestRepository"]


class GetPullRequestRepository(BaseModel):
    id: str
    pull_requests: "GetPullRequestRepositoryPullRequests" = Field(alias="pullRequests")


class GetPullRequestRepositoryPullRequests(BaseModel):
    nodes: Optional[List[Optional["GetPullRequestRepositoryPullRequestsNodes"]]]
    total_count: int = Field(alias="totalCount")


class GetPullRequestRepositoryPullRequestsNodes(BaseModel):
    id: str
    state: PullRequestState
    url: str
    base_ref_name: str = Field(alias="baseRefName")
    body: str
    title: str
    is_draft: bool = Field(alias="isDraft")
    base_commit: "GetPullRequestRepositoryPullRequestsNodesBaseCommit" = Field(alias="baseCommit")
    head_commit: "GetPullRequestRepositoryPullRequestsNodesHeadCommit" = Field(alias="headCommit")
    review_requests: Optional["GetPullRequestRepositoryPullRequestsNodesReviewRequests"] = Field(
        alias="reviewRequests"
    )
    timeline_items: "GetPullRequestRepositoryPullRequestsNodesTimelineItems" = Field(
        alias="timelineItems"
    )
    latest_reviews: Optional["GetPullRequestRepositoryPullRequestsNodesLatestReviews"] = Field(
        alias="latestReviews"
    )
    assignees: "GetPullRequestRepositoryPullRequestsNodesAssignees"
    labels: Optional["GetPullRequestRepositoryPullRequestsNodesLabels"]
    comments: "GetPullRequestRepositoryPullRequestsNodesComments"


class GetPullRequestRepositoryPullRequestsNodesBaseCommit(BaseModel):
    nodes: Optional[List[Optional["GetPullRequestRepositoryPullRequestsNodesBaseCommitNodes"]]]


class GetPullRequestRepositoryPullRequestsNodesBaseCommitNodes(BaseModel):
    commit: "GetPullRequestRepositoryPullRequestsNodesBaseCommitNodesCommit"


class GetPullRequestRepositoryPullRequestsNodesBaseCommitNodesCommit(BaseModel):
    parents: "GetPullRequestRepositoryPullRequestsNodesBaseCommitNodesCommitParents"


class GetPullRequestRepositoryPullRequestsNodesBaseCommitNodesCommitParents(BaseModel):
    nodes: Optional[
        List[Optional["GetPullRequestRepositoryPullRequestsNodesBaseCommitNodesCommitParentsNodes"]]
    ]


class GetPullRequestRepositoryPullRequestsNodesBaseCommitNodesCommitParentsNodes(BaseModel):
    oid: str


class GetPullRequestRepositoryPullRequestsNodesHeadCommit(BaseModel):
    nodes: Optional[List[Optional["GetPullRequestRepositoryPullRequestsNodesHeadCommitNodes"]]]


class GetPullRequestRepositoryPullRequestsNodesHeadCommitNodes(BaseModel):
    commit: "GetPullRequestRepositoryPullRequestsNodesHeadCommitNodesCommit"


class GetPullRequestRepositoryPullRequestsNodesHeadCommitNodesCommit(BaseModel):
    oid: str


class GetPullRequestRepositoryPullRequestsNodesReviewRequests(BaseModel):
    nodes: Optional[List[Optional["GetPullRequestRepositoryPullRequestsNodesReviewRequestsNodes"]]]


class GetPullRequestRepositoryPullRequestsNodesReviewRequestsNodes(BaseModel):
    requested_reviewer: Optional[
        Annotated[
            Union[
                "GetPullRequestRepositoryPullRequestsNodesReviewRequestsNodesRequestedReviewerBot",
                "GetPullRequestRepositoryPullRequestsNodesReviewRequestsNodesRequestedReviewerMannequin",
                "GetPullRequestRepositoryPullRequestsNodesReviewRequestsNodesRequestedReviewerTeam",
                "GetPullRequestRepositoryPullRequestsNodesReviewRequestsNodesRequestedReviewerUser",
            ],
            Field(discriminator="typename__"),
        ]
    ] = Field(alias="requestedReviewer")


class GetPullRequestRepositoryPullRequestsNodesReviewRequestsNodesRequestedReviewerBot(BaseModel):
    typename__: Literal["Bot"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesReviewRequestsNodesRequestedReviewerMannequin(
    BaseModel
):
    typename__: Literal["Mannequin"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesReviewRequestsNodesRequestedReviewerTeam(BaseModel):
    typename__: Literal["Team"] = Field(alias="__typename")
    slug: str
    id: str
    organization: "GetPullRequestRepositoryPullRequestsNodesReviewRequestsNodesRequestedReviewerTeamOrganization"


class GetPullRequestRepositoryPullRequestsNodesReviewRequestsNodesRequestedReviewerTeamOrganization(
    BaseModel
):
    login: str


class GetPullRequestRepositoryPullRequestsNodesReviewRequestsNodesRequestedReviewerUser(BaseModel):
    typename__: Literal["User"] = Field(alias="__typename")
    login: str
    id: str


class GetPullRequestRepositoryPullRequestsNodesTimelineItems(BaseModel):
    nodes: Optional[
        List[
            Optional[
                Annotated[
                    Union[
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesAddedToMergeQueueEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesAddedToProjectEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesAssignedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesAutoMergeDisabledEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesAutoMergeEnabledEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesAutoRebaseEnabledEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesAutoSquashEnabledEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesAutomaticBaseChangeFailedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesAutomaticBaseChangeSucceededEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesBaseRefChangedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesBaseRefDeletedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesBaseRefForcePushedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesClosedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesCommentDeletedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesConnectedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesConvertToDraftEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesConvertedNoteToIssueEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesConvertedToDiscussionEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesCrossReferencedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesDemilestonedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesDeployedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesDeploymentEnvironmentChangedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesDisconnectedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesHeadRefDeletedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesHeadRefForcePushedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesHeadRefRestoredEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesIssueComment",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesLabeledEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesLockedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesMarkedAsDuplicateEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesMentionedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesMergedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesMilestonedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesMovedColumnsInProjectEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesParentIssueAddedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesParentIssueRemovedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesPinnedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesPullRequestCommit",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesPullRequestCommitCommentThread",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesPullRequestReview",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesPullRequestReviewThread",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesPullRequestRevisionMarker",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesReadyForReviewEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesReferencedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesRemovedFromMergeQueueEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesRemovedFromProjectEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesRenamedTitleEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesReopenedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesReviewDismissedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesReviewRequestRemovedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesReviewRequestedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesSubIssueAddedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesSubIssueRemovedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesSubscribedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesTransferredEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesUnassignedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesUnlabeledEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesUnlockedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesUnmarkedAsDuplicateEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesUnpinnedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesUnsubscribedEvent",
                        "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesUserBlockedEvent",
                    ],
                    Field(discriminator="typename__"),
                ]
            ]
        ]
    ]


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesAddedToMergeQueueEvent(BaseModel):
    typename__: Literal["AddedToMergeQueueEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesAddedToProjectEvent(BaseModel):
    typename__: Literal["AddedToProjectEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesAssignedEvent(BaseModel):
    typename__: Literal["AssignedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesAutoMergeDisabledEvent(BaseModel):
    typename__: Literal["AutoMergeDisabledEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesAutoMergeEnabledEvent(BaseModel):
    typename__: Literal["AutoMergeEnabledEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesAutoRebaseEnabledEvent(BaseModel):
    typename__: Literal["AutoRebaseEnabledEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesAutoSquashEnabledEvent(BaseModel):
    typename__: Literal["AutoSquashEnabledEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesAutomaticBaseChangeFailedEvent(
    BaseModel
):
    typename__: Literal["AutomaticBaseChangeFailedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesAutomaticBaseChangeSucceededEvent(
    BaseModel
):
    typename__: Literal["AutomaticBaseChangeSucceededEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesBaseRefChangedEvent(BaseModel):
    typename__: Literal["BaseRefChangedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesBaseRefDeletedEvent(BaseModel):
    typename__: Literal["BaseRefDeletedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesBaseRefForcePushedEvent(BaseModel):
    typename__: Literal["BaseRefForcePushedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesClosedEvent(BaseModel):
    typename__: Literal["ClosedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesCommentDeletedEvent(BaseModel):
    typename__: Literal["CommentDeletedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesConnectedEvent(BaseModel):
    typename__: Literal["ConnectedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesConvertToDraftEvent(BaseModel):
    typename__: Literal["ConvertToDraftEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesConvertedNoteToIssueEvent(
    BaseModel
):
    typename__: Literal["ConvertedNoteToIssueEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesConvertedToDiscussionEvent(
    BaseModel
):
    typename__: Literal["ConvertedToDiscussionEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesCrossReferencedEvent(BaseModel):
    typename__: Literal["CrossReferencedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesDemilestonedEvent(BaseModel):
    typename__: Literal["DemilestonedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesDeployedEvent(BaseModel):
    typename__: Literal["DeployedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesDeploymentEnvironmentChangedEvent(
    BaseModel
):
    typename__: Literal["DeploymentEnvironmentChangedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesDisconnectedEvent(BaseModel):
    typename__: Literal["DisconnectedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesHeadRefDeletedEvent(BaseModel):
    typename__: Literal["HeadRefDeletedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesHeadRefForcePushedEvent(BaseModel):
    typename__: Literal["HeadRefForcePushedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesHeadRefRestoredEvent(BaseModel):
    typename__: Literal["HeadRefRestoredEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesIssueComment(BaseModel):
    typename__: Literal["IssueComment"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesLabeledEvent(BaseModel):
    typename__: Literal["LabeledEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesLockedEvent(BaseModel):
    typename__: Literal["LockedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesMarkedAsDuplicateEvent(BaseModel):
    typename__: Literal["MarkedAsDuplicateEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesMentionedEvent(BaseModel):
    typename__: Literal["MentionedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesMergedEvent(BaseModel):
    typename__: Literal["MergedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesMilestonedEvent(BaseModel):
    typename__: Literal["MilestonedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesMovedColumnsInProjectEvent(
    BaseModel
):
    typename__: Literal["MovedColumnsInProjectEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesParentIssueAddedEvent(BaseModel):
    typename__: Literal["ParentIssueAddedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesParentIssueRemovedEvent(BaseModel):
    typename__: Literal["ParentIssueRemovedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesPinnedEvent(BaseModel):
    typename__: Literal["PinnedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesPullRequestCommit(BaseModel):
    typename__: Literal["PullRequestCommit"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesPullRequestCommitCommentThread(
    BaseModel
):
    typename__: Literal["PullRequestCommitCommentThread"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesPullRequestReview(BaseModel):
    typename__: Literal["PullRequestReview"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesPullRequestReviewThread(BaseModel):
    typename__: Literal["PullRequestReviewThread"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesPullRequestRevisionMarker(
    BaseModel
):
    typename__: Literal["PullRequestRevisionMarker"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesReadyForReviewEvent(BaseModel):
    typename__: Literal["ReadyForReviewEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesReferencedEvent(BaseModel):
    typename__: Literal["ReferencedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesRemovedFromMergeQueueEvent(
    BaseModel
):
    typename__: Literal["RemovedFromMergeQueueEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesRemovedFromProjectEvent(BaseModel):
    typename__: Literal["RemovedFromProjectEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesRenamedTitleEvent(BaseModel):
    typename__: Literal["RenamedTitleEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesReopenedEvent(BaseModel):
    typename__: Literal["ReopenedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesReviewDismissedEvent(BaseModel):
    typename__: Literal["ReviewDismissedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesReviewRequestRemovedEvent(
    BaseModel
):
    typename__: Literal["ReviewRequestRemovedEvent"] = Field(alias="__typename")
    requested_reviewer: Optional[
        Annotated[
            Union[
                "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesReviewRequestRemovedEventRequestedReviewerBot",
                "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesReviewRequestRemovedEventRequestedReviewerMannequin",
                "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesReviewRequestRemovedEventRequestedReviewerTeam",
                "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesReviewRequestRemovedEventRequestedReviewerUser",
            ],
            Field(discriminator="typename__"),
        ]
    ] = Field(alias="requestedReviewer")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesReviewRequestRemovedEventRequestedReviewerBot(
    BaseModel
):
    typename__: Literal["Bot"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesReviewRequestRemovedEventRequestedReviewerMannequin(
    BaseModel
):
    typename__: Literal["Mannequin"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesReviewRequestRemovedEventRequestedReviewerTeam(
    BaseModel
):
    typename__: Literal["Team"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesReviewRequestRemovedEventRequestedReviewerUser(
    BaseModel
):
    typename__: Literal["User"] = Field(alias="__typename")
    login: str
    id: str


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesReviewRequestedEvent(BaseModel):
    typename__: Literal["ReviewRequestedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesSubIssueAddedEvent(BaseModel):
    typename__: Literal["SubIssueAddedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesSubIssueRemovedEvent(BaseModel):
    typename__: Literal["SubIssueRemovedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesSubscribedEvent(BaseModel):
    typename__: Literal["SubscribedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesTransferredEvent(BaseModel):
    typename__: Literal["TransferredEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesUnassignedEvent(BaseModel):
    typename__: Literal["UnassignedEvent"] = Field(alias="__typename")
    assignee: Optional[
        Annotated[
            Union[
                "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesUnassignedEventAssigneeBot",
                "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesUnassignedEventAssigneeMannequin",
                "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesUnassignedEventAssigneeOrganization",
                "GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesUnassignedEventAssigneeUser",
            ],
            Field(discriminator="typename__"),
        ]
    ]


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesUnassignedEventAssigneeBot(
    BaseModel
):
    typename__: Literal["Bot"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesUnassignedEventAssigneeMannequin(
    BaseModel
):
    typename__: Literal["Mannequin"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesUnassignedEventAssigneeOrganization(
    BaseModel
):
    typename__: Literal["Organization"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesUnassignedEventAssigneeUser(
    BaseModel
):
    typename__: Literal["User"] = Field(alias="__typename")
    login: str
    id: str


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesUnlabeledEvent(BaseModel):
    typename__: Literal["UnlabeledEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesUnlockedEvent(BaseModel):
    typename__: Literal["UnlockedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesUnmarkedAsDuplicateEvent(
    BaseModel
):
    typename__: Literal["UnmarkedAsDuplicateEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesUnpinnedEvent(BaseModel):
    typename__: Literal["UnpinnedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesUnsubscribedEvent(BaseModel):
    typename__: Literal["UnsubscribedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesUserBlockedEvent(BaseModel):
    typename__: Literal["UserBlockedEvent"] = Field(alias="__typename")


class GetPullRequestRepositoryPullRequestsNodesLatestReviews(BaseModel):
    nodes: Optional[List[Optional["GetPullRequestRepositoryPullRequestsNodesLatestReviewsNodes"]]]


class GetPullRequestRepositoryPullRequestsNodesLatestReviewsNodes(BaseModel):
    author: Optional[
        Annotated[
            Union[
                "GetPullRequestRepositoryPullRequestsNodesLatestReviewsNodesAuthorActor",
                "GetPullRequestRepositoryPullRequestsNodesLatestReviewsNodesAuthorUser",
            ],
            Field(discriminator="typename__"),
        ]
    ]
    viewer_did_author: bool = Field(alias="viewerDidAuthor")


class GetPullRequestRepositoryPullRequestsNodesLatestReviewsNodesAuthorActor(BaseModel):
    typename__: Literal["Actor", "Bot", "EnterpriseUserAccount", "Mannequin", "Organization"] = (
        Field(alias="__typename")
    )


class GetPullRequestRepositoryPullRequestsNodesLatestReviewsNodesAuthorUser(BaseModel):
    typename__: Literal["User"] = Field(alias="__typename")
    login: str
    id: str


class GetPullRequestRepositoryPullRequestsNodesAssignees(BaseModel):
    nodes: Optional[List[Optional["GetPullRequestRepositoryPullRequestsNodesAssigneesNodes"]]]


class GetPullRequestRepositoryPullRequestsNodesAssigneesNodes(BaseModel):
    login: str
    id: str


class GetPullRequestRepositoryPullRequestsNodesLabels(BaseModel):
    nodes: Optional[List[Optional["GetPullRequestRepositoryPullRequestsNodesLabelsNodes"]]]


class GetPullRequestRepositoryPullRequestsNodesLabelsNodes(BaseModel):
    name: str
    id: str


class GetPullRequestRepositoryPullRequestsNodesComments(BaseModel):
    nodes: Optional[List[Optional["GetPullRequestRepositoryPullRequestsNodesCommentsNodes"]]]


class GetPullRequestRepositoryPullRequestsNodesCommentsNodes(BaseModel):
    body: str
    id: str


GetPullRequest.model_rebuild()
GetPullRequestRepository.model_rebuild()
GetPullRequestRepositoryPullRequests.model_rebuild()
GetPullRequestRepositoryPullRequestsNodes.model_rebuild()
GetPullRequestRepositoryPullRequestsNodesBaseCommit.model_rebuild()
GetPullRequestRepositoryPullRequestsNodesBaseCommitNodes.model_rebuild()
GetPullRequestRepositoryPullRequestsNodesBaseCommitNodesCommit.model_rebuild()
GetPullRequestRepositoryPullRequestsNodesBaseCommitNodesCommitParents.model_rebuild()
GetPullRequestRepositoryPullRequestsNodesHeadCommit.model_rebuild()
GetPullRequestRepositoryPullRequestsNodesHeadCommitNodes.model_rebuild()
GetPullRequestRepositoryPullRequestsNodesReviewRequests.model_rebuild()
GetPullRequestRepositoryPullRequestsNodesReviewRequestsNodes.model_rebuild()
GetPullRequestRepositoryPullRequestsNodesReviewRequestsNodesRequestedReviewerTeam.model_rebuild()
GetPullRequestRepositoryPullRequestsNodesTimelineItems.model_rebuild()
GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesReviewRequestRemovedEvent.model_rebuild()
GetPullRequestRepositoryPullRequestsNodesTimelineItemsNodesUnassignedEvent.model_rebuild()
GetPullRequestRepositoryPullRequestsNodesLatestReviews.model_rebuild()
GetPullRequestRepositoryPullRequestsNodesLatestReviewsNodes.model_rebuild()
GetPullRequestRepositoryPullRequestsNodesAssignees.model_rebuild()
GetPullRequestRepositoryPullRequestsNodesLabels.model_rebuild()
GetPullRequestRepositoryPullRequestsNodesComments.model_rebuild()
