# Generated by ariadne-codegen
# Source: revup/github/queries/

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class GetTeam(BaseModel):
    organization: Optional["GetTeamOrganization"]


class GetTeamOrganization(BaseModel):
    team: Optional["GetTeamOrganizationTeam"]


class GetTeamOrganizationTeam(BaseModel):
    id: str
    members: "GetTeamOrganizationTeamMembers"


class GetTeamOrganizationTeamMembers(BaseModel):
    nodes: Optional[List[Optional["GetTeamOrganizationTeamMembersNodes"]]]
    total_count: int = Field(alias="totalCount")


class GetTeamOrganizationTeamMembersNodes(BaseModel):
    login: str


GetTeam.model_rebuild()
GetTeamOrganization.model_rebuild()
GetTeamOrganizationTeam.model_rebuild()
GetTeamOrganizationTeamMembers.model_rebuild()
