# Generated by ariadne-codegen
# Source: revup/github/schema/github.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import PullRequestUpdateState


class AddAssigneesToAssignableInput(BaseModel):
    assignable_id: str = Field(alias="assignableId")
    assignee_ids: List[str] = Field(alias="assigneeIds")
    client_mutation_id: Optional[str] = Field(alias="clientMutationId", default=None)


class AddCommentInput(BaseModel):
    body: str
    client_mutation_id: Optional[str] = Field(alias="clientMutationId", default=None)
    subject_id: str = Field(alias="subjectId")


class AddLabelsToLabelableInput(BaseModel):
    client_mutation_id: Optional[str] = Field(alias="clientMutationId", default=None)
    label_ids: List[str] = Field(alias="labelIds")
    labelable_id: str = Field(alias="labelableId")


class ConvertPullRequestToDraftInput(BaseModel):
    client_mutation_id: Optional[str] = Field(alias="clientMutationId", default=None)
    pull_request_id: str = Field(alias="pullRequestId")


class CreatePullRequestInput(BaseModel):
    base_ref_name: str = Field(alias="baseRefName")
    body: Optional[str] = None
    client_mutation_id: Optional[str] = Field(alias="clientMutationId", default=None)
    draft: Optional[bool] = False
    head_ref_name: str = Field(alias="headRefName")
    head_repository_id: Optional[str] = Field(alias="headRepositoryId", default=None)
    maintainer_can_modify: Optional[bool] = Field(alias="maintainerCanModify", default=True)
    repository_id: str = Field(alias="repositoryId")
    title: str


class MarkPullRequestReadyForReviewInput(BaseModel):
    client_mutation_id: Optional[str] = Field(alias="clientMutationId", default=None)
    pull_request_id: str = Field(alias="pullRequestId")


class RequestReviewsInput(BaseModel):
    client_mutation_id: Optional[str] = Field(alias="clientMutationId", default=None)
    pull_request_id: str = Field(alias="pullRequestId")
    team_ids: Optional[List[str]] = Field(alias="teamIds", default=None)
    union: Optional[bool] = False
    user_ids: Optional[List[str]] = Field(alias="userIds", default=None)


class UpdateIssueCommentInput(BaseModel):
    body: str
    client_mutation_id: Optional[str] = Field(alias="clientMutationId", default=None)
    id: str


class UpdatePullRequestInput(BaseModel):
    assignee_ids: Optional[List[str]] = Field(alias="assigneeIds", default=None)
    base_ref_name: Optional[str] = Field(alias="baseRefName", default=None)
    body: Optional[str] = None
    client_mutation_id: Optional[str] = Field(alias="clientMutationId", default=None)
    label_ids: Optional[List[str]] = Field(alias="labelIds", default=None)
    maintainer_can_modify: Optional[bool] = Field(alias="maintainerCanModify", default=None)
    milestone_id: Optional[str] = Field(alias="milestoneId", default=None)
    project_ids: Optional[List[str]] = Field(alias="projectIds", default=None)
    pull_request_id: str = Field(alias="pullRequestId")
    state: Optional[PullRequestUpdateState] = None
    title: Optional[str] = None
