# Generated by ariadne-codegen
# Source: revup/github/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class MarkReadyForReview(BaseModel):
    mark_pull_request_ready_for_review: Optional[
        "MarkReadyForReviewMarkPullRequestReadyForReview"
    ] = Field(alias="markPullRequestReadyForReview")


class MarkReadyForReviewMarkPullRequestReadyForReview(BaseModel):
    client_mutation_id: Optional[str] = Field(alias="clientMutationId")


MarkReadyForReview.model_rebuild()
