# Generated by ariadne-codegen
# Source: revup/github/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class RequestReviews(BaseModel):
    request_reviews: Optional["RequestReviewsRequestReviews"] = Field(alias="requestReviews")


class RequestReviewsRequestReviews(BaseModel):
    client_mutation_id: Optional[str] = Field(alias="clientMutationId")


RequestReviews.model_rebuild()
