# Generated by ariadne-codegen
# Source: revup/github/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class UpdatePullRequest(BaseModel):
    update_pull_request: Optional["UpdatePullRequestUpdatePullRequest"] = Field(
        alias="updatePullRequest"
    )


class UpdatePullRequestUpdatePullRequest(BaseModel):
    client_mutation_id: Optional[str] = Field(alias="clientMutationId")


UpdatePullRequest.model_rebuild()
