# Generated by ariadne-codegen
# Source: revup/github/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class UpdateIssueComment(BaseModel):
    update_issue_comment: Optional["UpdateIssueCommentUpdateIssueComment"] = Field(
        alias="updateIssueComment"
    )


class UpdateIssueCommentUpdateIssueComment(BaseModel):
    client_mutation_id: Optional[str] = Field(alias="clientMutationId")


UpdateIssueComment.model_rebuild()
